---

open_port: 5432/tcp

postgresql_streaming_user:
  name: replica
  pass: replica

postgresql_users:
  - { name: "centos", pass: "2Tdhj>70", flags: "LOGIN,SUPERUSER", db: 'database', search_path: ['search', 'path'] }
