---



- name: setting postgres
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/
    owner: postgres

- name: setting postgres hba
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/
    owner: postgres

  notify:
    - reload postgres
