---

- name: setting postgres
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: postgres
  when: ansible_facts['hostname'] == "master"

- name: setting postgres hba for master
  template:
    src: pg_hba.conf_master.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
  when: ansible_facts['hostname'] == "master"

- name: setting postgres hba for slave
  template:
    src: pg_hba.conf_slave.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
  when: ansible_facts['hostname'] == "slave"

  notify:
    - reload postgres
