---

- name: rm attr file
  file:
    path: /etc/resolv.conf
    attr: -i

- name: deploy resolv.conf template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager

- name: rm attr file
  file:
    path: /etc/resolv.conf
    attr: +i