---

- name: install epel
  dnf:
    name: epel-release
    state: present

- name: Install PostgreSQL
  dnf:
    name:
      - python3
      - postgresql-libs
      - postgresql
      - postgresql-contrib
      - postgresql-server
      - python3-psycopg2
    state: latest

- name: Install psycopg2
  pip:
    name: psycopg2

- name: init DB
  shell:
    cmd: postgresql-setup initdb

- name: Start and enable postgres
  service:
    name: postgresql
    enabled: yes
    state: started