---
- name: install firewall
  dnf:
    name: firewalld
    state: latest


- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open ports irewall
  firewalld:
    zone: public
    port: '{{open_port}}'
    permanent: true
    state: enabled

  notify:
    - reload firewall