---

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    daemon_reload: yes
    enabled: yes

- name: reload firewall
  service:
    name: firewalld
    state: reloaded
    daemon_reload: yes
    enabled: yes
