- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
  become_user: postgres
  #become_method: su
  become: true


- name: Create user
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres